### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by V-outsider** [Badiboy/pyCryptomusAPI#1]
Hi, you need to somehow specify the dependencies to automatically load them. Otherwise, I'll find out about the need for the requests library from a bug report.

Otherwise, you are great, keep it up, thanks for the module.

**Comment by Badiboy** [comment]
But...

![image](https://github.com/Badiboy/pyCryptomusAPI/assets/5613421/ade183da-05d8-4a55-9126-eb6e13bb9270)

and

![image](https://github.com/Badiboy/pyCryptomusAPI/assets/5613421/4b615092-7869-4259-9a37-d81cc2efe498)

Also works fine for github autotests...

**Comment by V-outsider** [comment]
I'm using the Poetry package manager and it didn't pull up requests. I don't think it's a major issue.

**Comment by V-outsider** [comment]
You can close this issue, if i will get more information about problem, i will make pull request or give you an info bro
